#!/usr/bin/env python3
"""Embed compiled RSX programs (*.vpo, *.fpo) as aligned C arrays: mkshaders.py out.h files..."""
import os, sys
out = ['/* generated by mkshaders.py */']
for path in sys.argv[2:]:
    data = open(path, 'rb').read()
    name = os.path.basename(path).replace('.', '_')
    out.append('static const unsigned char %s[%d] __attribute__((aligned(16))) = {' % (name, len(data)))
    for i in range(0, len(data), 16):
        out.append('    ' + ''.join('0x%02x,' % b for b in data[i:i + 16]))
    out.append('};')
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
